import type { Metadata } from "next";
import { Oleo_Script } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import {SessionProvider} from "next-auth/react";
import {Suspense} from "react";

const oleoScript = Oleo_Script({
  variable: "--font-oleo",
  weight: "400",
  subsets: ["latin"],
});

const oleoScriptBold = Oleo_Script({
  variable: "--font-oleo-bold",
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${oleoScript.variable} ${oleoScriptBold.variable} antialiased`}
      >
      <Suspense>
          <SessionProvider>
              <Header />

              <main className="flex-1">{children}</main>
              <Footer />
          </SessionProvider>
      </Suspense>
      </body>
    </html>
  );
}
